BLOCK_SITE:
- ''
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: https://miaopasixx.github.io/link/
  theme: common2
MAX_POSTS_NUM: 5
OUTDATE_CLEAN: 60
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: https://friend-json.pages.dev/friend.json
  list:
  - - "\u5B89\u77E5\u9C7C"
    - https://anzhiy.cn/
    - https://img02.anzhiy.cn/adminuploads/1/2022/09/15/63232b7d91d22.jpg
  - - Akilar
    - https://akilar.top
    - https://bu.dusays.com/2022/08/14/62f87864834ae.png
  - - "\u5F20\u6D2AHeo"
    - https://blog.zhheo.com
    - https://img.zhheo.com/i/2022/08/19/62ff32fa28da1.png
  - - "\u8F7B\u7B11Chuckle"
    - https://www.chuckle.top
    - https://cdn1.tianli0.top/npm/chuckle-js-css/chuckle/head.webp
  - - "Ariasaka\u306E\u5C0F\u7A9D"
    - https://yisous.xyz
    - https://bu.dusays.com/2022/10/22/6352dfd1f3fa3.png
  - - Tianli
    - https://tianli-blog.club
    - https://img1.tianli0.top/logo.png
  - - "\u8471\u82D3"
    - https://blog.itciraos.cn
    - https://bu.dusays.com/2023/01/07/63b96bd7565ce.png
  - - Fomalhaut??
    - https://www.fomal.cc
    - https://www.fomal.cc/assets/head.jpg
  - - "Vincent\u6587\u6714"
    - https://blog.vincent1230.top
    - //a.vincent1230.top/blogrol/avatar.jpg
  - - Hc's Blog
    - https://blog.ivil.top
    - https://blog.ivil.top/img/logo.png
  - - "\u5C0F\u57CE\u6545\u4E8B"
    - https://www.webxc.ml
    - https://npm.elemecdn.com/webxc/logo/logo.jpg
  - - "\u82B1\u8BED\u9601"
    - https://www.pigax.cn
    - http://q1.qlogo.cn/g?b=qq&nk=2033008907&s=640
  - - "\u866B\u4E0D\u77E5\u5594"
    - https://blog.ssycs.com
    - https://blog.ssycs.com/image/avatar.png
  - - "Ice \u306E\u5C0F\u7AD9"
    - https://081113.xyz
    - https://api.ixiaowai.cn/gqapi/gqapi.php
  - - Nuyoah
    - https://262259.xyz
    - https://q1.qlogo.cn/g?b=qq&nk=2152889763&s=100
  - - "\u5446\u9C7C"
    - https://daiyu-233.top
    - https://daiyu-233.top/img/avatar.png
  - - "Mghy \u306E Blog"
    - https://lmghy.top
    - https://cdn.staticaly.com/gh/MGHYGitHub/image-hosting@master/image-hosting/36d6c6eb3a95cbd0bdc4a70b221c5a6.7l7dzzhg0k00.webpg
  - - "Rainx\u2019s Blog"
    - https://rainxblog.top
    - https://rainxblog.top/wp-content/uploads/2022/11/head.jpg
  - - "LyShark - \u5B64\u98CE\u6D17\u5251"
    - https://www.lyshark.com
    - https://www.lyshark.com/images/baidu_logo.png
  - - lmx0
    - https://www.lmx0.top/
    - https://s1.vika.cn/space/2023/01/08/ccf7921738f741dbbd0a261c4b8fce1c
