BLOCK_SITE:
- ''
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: https://miaopasixx.github.io/link/
  theme: common2
MAX_POSTS_NUM: 5
OUTDATE_CLEAN: 60
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: https://raw.githubusercontent.com/miaopasixx/friends/master/friend.json
  list:
